### ISSUE TITLE
is there still a support server?

### ISSUE THREAD

**Issue by seiyria** [mikolajkalwa/GamesDealsBot#4]
sorry for posting here, the bot was only available from this site: https://dsc.cool/bot/396466836331429889

I am trying to set it up in a new server but the bot never seems to respond to commands. is something wrong with it?

**Comment by mikolajkalwa** [comment]
Sorry for late response. Support server was removed when I couldn't afford to host the bot (server fees were higher than I could handle at that time). 
I'd like to bring it back soon, but I need to look into the code and rewrite some parts from scratch.

**Comment by seiyria** [comment]
Weird, are you not the one hosting the current bot then? It's currently running as far as I can tell.

**Comment by mikolajkalwa** [comment]
The bot itself is down. so it's impossible to add it to a new Discord server.
But the service which sends notifications with found games is up and running because it requires much fewer resources than the bot did.
As I said before, I'd like to bring the project back to life. 
Discord.js seems to be not the best choice for a slightly bigger bot. I have plans to rewrite it with typescript and eris.js

**Comment by seiyria** [comment]
I see! Thanks for clarifying. I've only ever made a bot that's up 24/7 so this is new to me. 

Best of luck with the rewrite. I definitely like the typescript route and while I'm not familiar with eris.js,I have a framework I use for my bots that might be of interest: https://github.com/seiyria/DiscordBotExample

Though it really only covers the core. Not sure how well it scales since my bots are generally only in a few servers at most.
